from __future__ import annotations

from pathlib import Path
import argparse
import math
import sys

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


def find_phi4_csv(data_dir: Path) -> Path | None:
    """Find a phi4 baseline CSV, preferring phi4_samples.csv."""
    preferred = data_dir / "phi4_samples.csv"
    if preferred.exists():
        print(f"[found] preferred file: {preferred.name}")
        return preferred.resolve()

    patterns = [
        "phi4*.csv",
        "*phi4*.csv",
        "**/phi4*.csv",
        "**/*phi4*.csv",
    ]
    matches = []
    for pat in patterns:
        matches.extend(data_dir.glob(pat))

    matches = sorted({p.resolve() for p in matches if p.exists() and p.suffix.lower() == ".csv"})
    if not matches:
        return None

    chosen = sorted(matches, key=lambda p: (len(p.name), p.name))[0]
    print(f"[found] auto-detected file: {chosen.name}")
    return chosen


def summarize_phi4(df: pd.DataFrame) -> pd.DataFrame:
    required = ["label", "t_tr"]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns: {missing}")

    rows = []
    for label, g in sorted(df.groupby("label"), key=lambda x: float(x[0])):
        t = pd.to_numeric(g["t_tr"], errors="coerce").dropna()
        n = len(t)
        sd = float(t.std(ddof=1)) if n > 1 else np.nan
        se = float(sd / math.sqrt(n)) if n > 1 else np.nan
        rows.append(
            {
                "label": float(label),
                "n": n,
                "t_tr_mean": float(t.mean()) if n > 0 else np.nan,
                "t_tr_sd": sd,
                "t_tr_se": se,
            }
        )
    return pd.DataFrame(rows)


def save_in_formats(fig, basepath: Path, formats: list[str], dpi: int):
    for fmt in formats:
        out = basepath.with_suffix(f".{fmt}")
        fig.savefig(
            out,
            dpi=dpi if fmt.lower() in {"png", "jpg", "jpeg", "tif", "tiff"} else None,
            bbox_inches="tight",
        )
        print(f"[saved] {out}")


def plot_phi4_baseline(
    summary: pd.DataFrame,
    basepath: Path,
    formats: list[str],
    dpi: int,
    with_titles: bool,
    show_samples: bool,
    raw_df: pd.DataFrame,
):
    fig, ax = plt.subplots(figsize=(6, 4.5))

    x = summary["label"].to_numpy()
    y = summary["t_tr_mean"].to_numpy()
    yerr = summary["t_tr_se"].to_numpy()

    if show_samples:
        for label, g in sorted(raw_df.groupby("label"), key=lambda x: float(x[0])):
            t = pd.to_numeric(g["t_tr"], errors="coerce").dropna().to_numpy()
            xvals = np.full_like(t, fill_value=float(label), dtype=float)
            ax.plot(xvals, t, linestyle="none", marker="o", alpha=0.45, markersize=4)

    ax.errorbar(x, y, yerr=yerr, marker="o", capsize=3)
    ax.set_xticks(x)
    ax.set_xticklabels([f"{v:.2f}" for v in x])
    ax.set_xlabel("Initial-state label")
    ax.set_ylabel(r"Mean transition time $t_{\mathrm{tr}}$")

    if with_titles:
        ax.set_title("phi4 baseline transition time")

    fig.tight_layout()
    save_in_formats(fig, basepath, formats, dpi)
    plt.close(fig)


def write_readme(outdir: Path, csv_name: str, formats: list[str]):
    text = f"""# phi4 baseline figure

Generated by `tdgl_phi4_baseline_figure.py`.

## Input CSV
- `{csv_name}`

## Output
- `phi4_baseline_transition_time` in formats: {', '.join(formats)}
- `phi4_baseline_summary.csv`

## Figure meaning
This figure shows the mean transition time $t_{{\mathrm{{tr}}}}$ as a function of the initial-state label for the phi4 baseline dataset.
Error bars indicate the standard error over samples.

## Suggested manuscript usage
- Main Fig. 1: phi4 baseline
"""
    (outdir / "README_phi4_baseline_figure.md").write_text(text, encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description="Generate a manuscript-ready phi4 baseline figure.")
    parser.add_argument("--data-dir", default=".", help="Directory containing phi4_samples.csv. Default: current directory.")
    parser.add_argument("--outdir", default="phi4_baseline_figure", help="Output directory.")
    parser.add_argument("--formats", default="png,pdf", help="Comma-separated output formats. Example: png,pdf")
    parser.add_argument("--dpi", type=int, default=300, help="Raster DPI for PNG output.")
    parser.add_argument("--with-titles", action="store_true", help="Add a title for debugging/presentation use.")
    parser.add_argument("--show-samples", action="store_true", help="Overlay individual sample points.")
    args = parser.parse_args()

    data_dir = Path(args.data_dir).resolve()
    outdir = Path(args.outdir)
    if not outdir.is_absolute():
        outdir = data_dir / outdir
    outdir.mkdir(parents=True, exist_ok=True)

    formats = [x.strip().lower() for x in args.formats.split(",") if x.strip()]
    if not formats:
        formats = ["png", "pdf"]

    print(f"[data-dir] {data_dir}")
    print(f"[outdir]   {outdir}")

    csv_path = find_phi4_csv(data_dir)
    if csv_path is None:
        print("No phi4 CSV file was found.")
        print('Example: python tdgl_phi4_baseline_figure.py --data-dir "C:\\path\\to\\csv_folder"')
        visible = sorted(data_dir.glob("*.csv"))
        if visible:
            print("Visible CSV files:")
            for p in visible[:50]:
                print(" ", p.name)
        sys.exit(1)

    df = pd.read_csv(csv_path)
    summary = summarize_phi4(df)
    summary.to_csv(outdir / "phi4_baseline_summary.csv", index=False)
    print(f"[saved] {outdir / 'phi4_baseline_summary.csv'}")

    plot_phi4_baseline(
        summary=summary,
        basepath=outdir / "phi4_baseline_transition_time",
        formats=formats,
        dpi=args.dpi,
        with_titles=args.with_titles,
        show_samples=args.show_samples,
        raw_df=df,
    )

    write_readme(outdir, csv_path.name, formats)
    print(f"[saved] {outdir / 'README_phi4_baseline_figure.md'}")
    print(f"\nDone. Outputs written to: {outdir}")


if __name__ == "__main__":
    main()
